name: Kernel Derleyici (32-bit ARM)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3

      - name: Bağımlılıkları Kur
        run: |
          sudo apt update
          sudo apt install -y build-essential bc libncurses5-dev libssl-dev bison flex libelf-dev gcc-arm-linux-gnueabi

      - name: Derlemeyi Başlat
        run: |
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabi-
          # Klasördeki defconfig adını buraya tam yaz (Örn: msm8917_defconfig)
          make j6primelte_defconfig 
          make -j$(nproc)

      - name: Dosyayı Hazırla
        run: |
          mkdir output
          # 32-bit ARM kernel çıktısı genelde zImage-dtb olur
          if [ -f arch/arm/boot/zImage-dtb ]; then
            cp arch/arm/boot/zImage-dtb output/
          elif [ -f arch/arm/boot/zImage ]; then
            cp arch/arm/boot/zImage output/
          fi

      - name: Sonucu Yükle
        uses: actions/upload-artifact@v3
        with:
          name: J6-Plus-32Bit-Kernel
          path: output/*
